name: 'Toggle awaiting-reply label of issue'
description: 'Toggle awaiting-reply or any label when issue author or team member comment on issue.'
author: jd-0001
branding:
  icon: award
  color: purple
inputs:
  token:
    description: "GitHub token"
    required: false
    default: ${{ github.token }}
  label:
    description: 'Label to toggle when author or team member comment on issue'
    required: true
  # member-association:
  #   # https://docs.github.com/en/graphql/reference/enums#commentauthorassociation
  #   description: 'Repository associations that are considered part of the team. The action will skip the labeling logic if the user who created the comment falls into one of these groups. Separate multiple with commas (eg. "OWNER, MEMBER")'
  #   required: false
  #   default: "OWNER, MEMBER, COLLABORATOR"
  ignore-label:
    description: 'Ignore toggling label when this label is found on the issue.'
    required: false
  only-if-label:
    description: 'Only perform toggling if this label is found on the issue.'
    required: false
  exclude-members:
    description: 'Ignore operation if commented by team member but present in exclude-members'
    required: false
  remove-only-if-author:
    description: 'Remove label only if author comments on issue'
    required: false
    default: false
  debug:
    description: "Debug the action which will print more information on how its running and what's processing"
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'